### ISSUE TITLE
Folder icon issue

### ISSUE THREAD

**Issue by RedBearAK** [USBA/iOS-iCons#4]
This is a great icon set, but it seems to have an issue with the folder icons in certain situations, which I hope we can fix somehow. 

The Transmission bittorrent app is the main example I can show: 

![folder_icons_issue_yaru](https://user-images.githubusercontent.com/64876997/148492941-074ef273-9dd8-4413-a7a5-bb4ae021a699.png)
With the Yaru icon set. 

![folder_icons_issue_cupertino-monterey](https://user-images.githubusercontent.com/64876997/148493010-96dbd097-fbc0-4898-840c-4ac1d48e554d.png)
With Cupertino-Monterey icon set. 

Everything works fine at all sizes in Nautilus. Adwaita, HiColor, Ubuntu-Mono and other icon sets don't display this issue with Transmission.

**Comment by aniketgawande1** [comment]
To resolve the folder icon issue in the Transmission bittorrent app with the Yaru and Cupertino-Monterey icon sets, you can try the following steps:

### 1. **Check Icon Sizes:**
   - The problem might be related to the specific sizes of the icons in the Yaru and Cupertino-Monterey sets. Verify that the icon sizes match the required dimensions for Transmission.
   - Ensure that the `scalable` folder or the 16x16, 24x24, 32x32, etc., icons exist in the icon set.

### 2. **Override the Icons:**
   - You can manually override the icons in the Transmission app by copying the folder icons from a working set (like Adwaita) into the Yaru or Cupertino-Monterey icon directory.
   - Place the copied icons into the appropriate folder sizes (e.g., `16x16`, `24x24`) within the icon set directory (usually found in `/usr/share/icons` or `~/.icons`).

### 3. **Update Icon Cache:**
   - After making changes, update the icon cache with the following command:
     ```bash
     sudo gtk-update-icon-cache /usr/share/icons/<icon_theme_name>
     ```
     Replace `<icon_theme_name>` with the name of the icon theme you’re modifying.

### 4. **Check for Missing Symlinks:**
   - Sometimes, missing symlinks in the icon set can cause issues. Ensure that symlinks for the folder icons point to the correct icon files.

### 5. **Use a Different Icon Theme:**
   - If the problem persists, consider using a different icon set or reporting the issue to the maintainers of the Yaru and Cupertino-Monterey icon sets for a potential fix.

**Comment by aniketgawande1** [comment]
To resolve the folder icon issue in the Transmission bittorrent app with the Yaru and Cupertino-Monterey icon sets, you can try the following steps:

### 1. **Check Icon Sizes:**
   - The problem might be related to the specific sizes of the icons in the Yaru and Cupertino-Monterey sets. Verify that the icon sizes match the required dimensions for Transmission.
   - Ensure that the `scalable` folder or the 16x16, 24x24, 32x32, etc., icons exist in the icon set.

### 2. **Override the Icons:**
   - You can manually override the icons in the Transmission app by copying the folder icons from a working set (like Adwaita) into the Yaru or Cupertino-Monterey icon directory.
   - Place the copied icons into the appropriate folder sizes (e.g., `16x16`, `24x24`) within the icon set directory (usually found in `/usr/share/icons` or `~/.icons`).

### 3. **Update Icon Cache:**
   - After making changes, update the icon cache with the following command:
     ```bash
     sudo gtk-update-icon-cache /usr/share/icons/<icon_theme_name>
     ```
     Replace `<icon_theme_name>` with the name of the icon theme you’re modifying.

### 4. **Check for Missing Symlinks:**
   - Sometimes, missing symlinks in the icon set can cause issues. Ensure that symlinks for the folder icons point to the correct icon files.

### 5. **Use a Different Icon Theme:**
   - If the problem persists, consider using a different icon set or reporting the issue to the maintainers of the Yaru and Cupertino-Monterey icon sets for a potential fix.

**Comment by RedBearAK** [comment]
That looks like something that was entirely composed by ChatGPT 4. Nothing wrong with that, but there's no attribution. 

Anyway, I forgot all about this issue and doubt this is still a problem.
